repos:
  - repo: local
    hooks:
      - id: pylint-wrapper
        name: Run pylint wrapper
        entry: python ./src/.tools/pylint.py
        language: python
        additional_dependencies: ["pylint>=3.0.0", "pytest>=8.0.0"]
        pass_filenames: false
        stages: [pre-commit, pre-push]
      - id: tests
        name: Run tests
        entry: python -m pytest
        language: python
        additional_dependencies: ["pytest>=8.0.0"]
        pass_filenames: false
        stages: [pre-commit, pre-push]
